### PR TITLE
Upgrade to Spring-boot 1.5.1

### LINKED ISSUE #10: Fails with Spring Boot 1.5.x
Due to a deprecated class that was removed in Spring Boot 1.5.x this project no longer seems to work. It looks like a class you were using was moved to a different package.

### PR DESCRIPTION
**Pull request by kestemm**
Fixes #10

### CODE REVIEW

**Comment by hopperd** [comment]
Any reason that this pull request hasn't been merged in?

**Comment by richard-hulm** [comment]
Saw this after raising mine... Would be very happy for either one to be merged!

**Comment by dushanhanuska** [comment]
Is there any update on when this can be merged? This is currently preventing me to upgrade my projects to SpringBoot 1.5.

**Comment by dushanhanuska** [comment]
Thanks!

**Pull request merged**
